.PHONY: clean All

All:
	@echo "----------Building project:[ UOCProgrammeEC - Debug ]----------"
	@cd "UOCProgrammeEC" && "$(MAKE)" -f  "UOCProgrammeEC.mk"
clean:
	@echo "----------Cleaning project:[ UOCProgrammeEC - Debug ]----------"
	@cd "UOCProgrammeEC" && "$(MAKE)" -f  "UOCProgrammeEC.mk" clean
